public class Lab1 {
    public static void main(String[] args) {
    /*
    f we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3,
    5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples
    of 3 or 5 below 1000.
     */
        int total = 0;
        int i;
        for (i=0; i < 1000 ; i ++){
            if ((i % 3 == 0) || (i % 5 == 0) ){
                System.out.println("Adding " + i + "to Total : " + total);
                total = total + i;
                System.out.println("New Total : " + total);
            }
        }
        System.out.println("The Total is : " + total);
    /*
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, . . .
    By considering the terms in the Fibonacci sequence whose values do not exceed
    four million, find the sum of the even-valued terms.

     */
        System.out.println("PROBLEM 2 STARTS HERE");
        int nextNumber;
        int num1 = 1;
        int num2 = 2;
        int totals = 0;

        for (int x = 0; x < 4000000 ; x++){
            nextNumber = num1 + num2;
            //System.out.println("next number : " + nextNumber);
            num1 = num2;
            //System.out.println("num 1 :" + num1);
            num2 = nextNumber;
            //System.out.println("num 2 :" + num2);
            if (num2 % 2 == 0){
                //System.out.println("Adding : " + num2 + "to " + totals);
               totals += num2;
            }
        }
        System.out.println("Total is :" + totals);

    }
}
